# Site settings
title: Code Words
email: nicolemairead4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    '“I'm just a girl, standing in front of a computer, asking it to love her.” -- Julia Roberts' -- Nicole Witte
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  nwitte4
# Build settings
markdown: kramdown
